language: node_js
node_js:
  - iojs-v1
  - iojs-v2
  - iojs-v3
  - 6
  - 5
  - 4
  - 0.12
matrix:
  allow_failures:
    - node_js: "0.10"
  fast_finish: true
script: "npm run-script test"
after_script:
  - "npm install coveralls codecov.io"
  - "cat ./coverage/lcov.info | coveralls"
  - "cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js"
